### ISSUE TITLE
feat: create a dictionary for messages

### ISSUE THREAD

**Issue by Dan0xE** [TOwInOK/Minecraft-Dependency-Manager#7]
we should create something like a dictionary for messages to have them in multiple languages, something similar like [i18next](https://www.i18next.com/)

**Comment by TOwInOK** [comment]
If we talk about i18next (Example i18next for rust -> https://github.com/longbridgeapp/rust-i18n), this tool provides quite a lot of features that we don't really need. In this case we need to be able to translate phrases that will not change during the program. 

So, I made a simplified version with 1 language file.
